// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr0NkoK88MUN8fAtpty2JZR6I-Kc4Wb6M',
    appId: '1:793938698587:web:1f5fe20a30233454d23a7e',
    messagingSenderId: '793938698587',
    projectId: 'modul-3-44f7d',
    authDomain: 'modul-3-44f7d.firebaseapp.com',
    storageBucket: 'modul-3-44f7d.appspot.com',
    measurementId: 'G-D1V35R51S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8Qrp4iPvviJ_-xaum5wlWPbjX2fRBBQ',
    appId: '1:793938698587:android:e887fa32f63492b6d23a7e',
    messagingSenderId: '793938698587',
    projectId: 'modul-3-44f7d',
    storageBucket: 'modul-3-44f7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZiY27SzbBN0g16ulyaQ31ldeiVl-6bhg',
    appId: '1:793938698587:ios:7d8a0ef01b9f7041d23a7e',
    messagingSenderId: '793938698587',
    projectId: 'modul-3-44f7d',
    storageBucket: 'modul-3-44f7d.appspot.com',
    iosBundleId: 'com.example.codelab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZiY27SzbBN0g16ulyaQ31ldeiVl-6bhg',
    appId: '1:793938698587:ios:7d8a0ef01b9f7041d23a7e',
    messagingSenderId: '793938698587',
    projectId: 'modul-3-44f7d',
    storageBucket: 'modul-3-44f7d.appspot.com',
    iosBundleId: 'com.example.codelab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr0NkoK88MUN8fAtpty2JZR6I-Kc4Wb6M',
    appId: '1:793938698587:web:e2fa0ef9ce5bf359d23a7e',
    messagingSenderId: '793938698587',
    projectId: 'modul-3-44f7d',
    authDomain: 'modul-3-44f7d.firebaseapp.com',
    storageBucket: 'modul-3-44f7d.appspot.com',
    measurementId: 'G-QH0F95XCML',
  );

}